import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";

import NavBar from "@/components/ui/Navbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     
     
        <NavBar></NavBar>
        {children}
   
    
    
    </html>
  );
}
